apiVersion: v1
kind: Service
metadata:
  name: tempo-s3-shard-service
  labels:
    app: tempo-s3-shard
spec:
  type: ClusterIP
  ports:
  - port: 8080
    targetPort: 8080
    protocol: TCP
    name: http
  selector:
    app: tempo-s3-shard